# Generated by Django 6.0.4 on 2026-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitapp', '0004_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
