# Generated by Django 6.0.4 on 2026-04-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixitapp', '0006_remove_booking_phone_number_booking_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='worker_phone',
        ),
    ]
